export const paths = {
  home: "/",
  jury: "/jury",
  juryExplore: "/jury/explore",
  my: "/my",
  myJuryActivity: "/my/jury-activity",
  myCases: "/my/cases",
  myCaseDetail: (caseId: number | string) => `/my/cases/${caseId}`,
  myCaseDetailPattern: "/my/cases/:caseId",
  myCaseReason: (caseId: number | string) => `/my/cases/${caseId}/reason`,
  myCaseReasonPattern: "/my/cases/:caseId/reason",
  upload: "/judgment/upload",
  received: "/judgment/received",
  confirm: "/judgment/confirm",
  judging: "/judgment/judging",
  verdict: "/judgment/verdict",
  verdictResult: "/judgment/verdict/result",
  verdictReason: "/judgment/verdict/reason",
  juryRequest: "/judgment/verdict/jury",
  login: "/login",
} as const;
